apiVersion: apps/v1
kind: Deployment

metadata:
  name: myapp
  labels:
    app: myapp

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: myapp

  template:
    metadata:
      labels:
        app: myapp

    spec:
      imagePullSecrets:
{{- toYaml .Values.imagePullSecrets | nindent 8 }}

      containers:
        - name: myapp
          image: "{{ .Values.image.repository }}{{- if .Values.image.tag }}:{{ .Values.image.tag }}{{- end }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: 8080